# Generated by Django 4.2.3 on 2024-06-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplierid',
            field=models.CharField(db_column='supplier_id', default='', max_length=99),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='supplierid',
            field=models.CharField(db_column='supplier_id', default='', max_length=99),
            preserve_default=False,
        ),
    ]
