# Generated by Django 4.2.3 on 2024-06-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_order_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='propcode',
        ),
    ]
