# Generated by Django 4.2.3 on 2024-06-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_remove_users_propcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_order',
            name='supplierid',
            field=models.CharField(db_column='supplier_id', default=1, max_length=99),
            preserve_default=False,
        ),
    ]
