# Generated by Django 4.2.3 on 2024-06-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_remove_log_order_logdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, db_column='dispatch_status', max_length=99),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplierid',
            field=models.CharField(blank=True, db_column='supplier_id', max_length=99),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalprice',
            field=models.DecimalField(blank=True, db_column='total_price', decimal_places=2, max_digits=19),
        ),
    ]
