# Generated by Django 4.2.3 on 2024-06-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_alter_order_status_alter_order_supplierid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='orderid',
            field=models.IntegerField(db_column='order_id', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log_order',
            name='orderid',
            field=models.IntegerField(db_column='order_id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buyerid',
            field=models.IntegerField(blank=True, db_column='buyer_id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.IntegerField(blank=True, db_column='order_id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='productid',
            field=models.IntegerField(blank=True, db_column='product_id'),
        ),
    ]
