# Generated by Django 4.2.3 on 2024-06-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_review_orderid_alter_log_order_orderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='item_name', max_length=99, unique=True),
        ),
    ]
