# Generated by Django 4.2.3 on 2024-06-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0011_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.IntegerField(blank=True, db_column='order_id', unique=True),
        ),
    ]
