# Generated by Django 4.2.3 on 2024-06-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0012_alter_order_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(blank=True, db_column='group', max_length=10),
        ),
    ]
