# Generated by Django 4.2.3 on 2024-06-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0013_alter_users_group'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
