# Generated by Django 4.2.3 on 2024-06-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0014_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_column='item_name', max_length=99),
        ),
    ]
